/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class"],
  theme: {
    extend: {
      colors: {
        hermes: {
          blue: "#0000f2",
          dark: "#00009c",
          midnight: "#000066",
          paper: "#f5f5f7",
          white: "#ffffff",
          fg: "#f2f2f2",
          ink: "#050518",
          charcoal: "#3a3a52",
          muted: "#8585c5",
          accent: "#00e5ff",
          warning: "#ff9900",
          critical: "#ff3333",
          safe: "#00e676",
        },
        obsidian: "#050518",
        paper: "#ffffff",
        cloud: "#f4f4f8",
        ink: "#050518",
        charcoal: "#404058",
        slate: "#707090",
        "sky-tint": "#e6e6ff",
        accent: "#0000f2",
        critical: "#ff2222",
        warning: "#ff8800",
        safe: "#00cc66",
      },
      fontFamily: {
        sans: ["Bahnschrift", '"DIN Alternate"', '"DIN Condensed"', '"Franklin Gothic Medium"', "system-ui", "sans-serif"],
        heading: ["Bahnschrift", '"DIN Alternate"', '"DIN Condensed"', '"Franklin Gothic Medium"', "system-ui", "sans-serif"],
        display: ["Bahnschrift", '"DIN Alternate"', '"DIN Condensed"', '"Franklin Gothic Medium"', "system-ui", "sans-serif"],
        body: ["Bahnschrift", '"DIN Alternate"', '"DIN Condensed"', '"Franklin Gothic Medium"', "system-ui", "sans-serif"],
        mono: ["Bahnschrift", '"JetBrains Mono"', "SF Mono", "monospace"],
      },
      borderRadius: {
        none: "0px",
        sm: "2px",
        DEFAULT: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        pill: "9999px",
        card: "8px",
        "card-lg": "12px",
      },
      boxShadow: {
        hermes: "0 10px 30px rgba(0, 0, 242, 0.25)",
        lift: "0 8px 20px rgba(0, 0, 0, 0.12)",
        press: "0 2px 6px rgba(0, 0, 0, 0.2)",
        terminal: "0 20px 50px rgba(0, 0, 0, 0.4)",
      },
    },
  },
  plugins: [],
};
