import type { ScenarioPreset, CameraFeed, AuditRecord } from "./types";

export const SAMPLE_SCENARIOS: ScenarioPreset[] = [
  {
    id: "dawn-construction",
    title: "Dawn Dusk Low-Light",
    site: "North Industrial Excavation — Zone 4",
    camera: "CAM-04 (Perimeter Tower)",
    condition: "Low Light / Dawn (12.4 Lux)",
    tag: "Low Light",
    description: "Dawn lighting obscuring workers operating in the swing radius of a 30-ton excavator. Discern detects low ambient illumination, engages OpenCV CLAHE + Gamma restoration, locates workers with YOLOv8n, and identifies missing helmet and unsafe proximity.",
    photoUrl: "https://images.unsplash.com/photo-1776594974675-b21647efe342?w=1600&q=80&auto=format&fit=crop",
    photoCredit: "Markus Kammermann / Unsplash",
    rawFilter: "brightness(0.4) contrast(0.95) saturate(0.7)",
    restoredFilter: "brightness(1.05) contrast(1.12) saturate(1.05)",
    analysis: {
      scene: {
        setting: "Construction site, excavation trench with heavy excavator",
        lighting: "low_light",
        weather: "clear",
        visibility: "reduced",
        human_presence: true,
        machinery_presence: true,
        summary: "Dawn low-light environment at active construction excavation zone with heavy tracked machinery and multiple ground personnel.",
      },
      plan: {
        restoration_tools: ["low_light_enhancement"],
        detection_tools: ["person_detection", "ppe_reasoning", "zone_reasoning"],
        reasoning: "Lighting is severely degraded at dawn (12 Lux), reducing contrast around worker heads and hazard boundaries. Low-light enhancement (CLAHE + Gamma 1.8) selected to expose shadow detail before YOLOv8n inference and Gemini PPE reasoning.",
      },
      steps: [
        { name: "Scene understanding", status: "completed", detail: "Dawn excavation site, low visibility, human & machinery detected", duration_ms: 382 },
        { name: "Tool selection", status: "completed", detail: "Selected CLAHE enhancement, YOLOv8n, PPE & Zone compliance", duration_ms: 12 },
        { name: "Restoration (OpenCV CLAHE)", status: "completed", detail: "Applied CLAHE contrast limit 3.0 + Gamma boost 1.8", duration_ms: 18 },
        { name: "Person detection (YOLOv8n)", status: "completed", detail: "2 persons localized with 94% and 98% confidence", duration_ms: 31 },
        { name: "Violation reasoning (Gemini)", status: "completed", detail: "2 active violations identified (Missing Helmet, Zone Breach)", duration_ms: 410 },
      ],
      detections: [
        {
          id: "p1",
          label: "Person 1",
          confidence: 0.94,
          box: { x: 530, y: 380, width: 70, height: 155 },
          source: "yolov8n_restored",
        },
        {
          id: "p2",
          label: "Person 2",
          confidence: 0.98,
          box: { x: 220, y: 410, width: 68, height: 148 },
          source: "yolov8n_restored",
        },
      ],
      violations: [
        {
          id: "v1",
          type: "missing_ppe",
          severity: "critical",
          description: "Worker (Person 1) is operating without a required Type I/II protective hard hat in an active heavy machinery excavation quadrant.",
          related_detection_ids: ["p1"],
          oshaCode: "OSHA 1926.100(a)",
          recommendation: "Immediate radio alert to Site Foreman to halt worker and mandate certified head protection.",
        },
        {
          id: "v2",
          type: "restricted_zone",
          severity: "critical",
          description: "Worker (Person 1) is positioned inside the 15-meter swing radius danger zone of operating tracked excavator without spotter coordination.",
          related_detection_ids: ["p1"],
          oshaCode: "OSHA 1926.600(a)(6)",
          recommendation: "Trigger audible perimeter exclusion alarm and verify clear line-of-sight.",
        },
      ],
      annotated_image: "https://images.unsplash.com/photo-1776594974675-b21647efe342?w=1600&q=80&auto=format&fit=crop",
      raw_image: "https://images.unsplash.com/photo-1776594974675-b21647efe342?w=1600&q=80&auto=format&fit=crop",
      restored_image: "https://images.unsplash.com/photo-1776594974675-b21647efe342?w=1600&q=80&auto=format&fit=crop",
    },
  },
  {
    id: "fog-maritime-port",
    title: "Dense Maritime Sea Fog",
    site: "Port Logistics Terminal — Berth 7 Gantry",
    camera: "CAM-12 (Quay Gantry South)",
    condition: "Dense Sea Fog / Visibility < 30m",
    tag: "Dense Fog",
    description: "Coastal fog rolls in over container loading berths, scattering light and obscuring dock workers near automated straddle carriers. Discern deploys Dark-Channel Prior Dehazing before running zone violation checks.",
    photoUrl: "https://images.unsplash.com/photo-1706499856012-14f062c72b49?w=1600&q=80&auto=format&fit=crop",
    photoCredit: "Unsplash",
    rawFilter: "brightness(1.15) contrast(0.55) saturate(0.4) blur(1.5px)",
    restoredFilter: "contrast(1.22) saturate(1.1) brightness(1.02)",
    analysis: {
      scene: {
        setting: "Maritime container terminal berth, wet pavement, overhead gantry crane",
        lighting: "normal",
        weather: "fog",
        visibility: "poor",
        human_presence: true,
        machinery_presence: true,
        summary: "Dense maritime advection fog causing severe atmospheric scattering and masking quay boundaries.",
      },
      plan: {
        restoration_tools: ["dehaze"],
        detection_tools: ["person_detection", "ppe_reasoning", "zone_reasoning"],
        reasoning: "Atmospheric transmission is reduced below 25% due to aerosol fog particles. Fast Dark-Channel Prior Dehazing applied to recover edge sharpness before person detection.",
      },
      steps: [
        { name: "Scene understanding", status: "completed", detail: "Port berth, dense fog, poor visibility, gantry machinery active", duration_ms: 395 },
        { name: "Tool selection", status: "completed", detail: "Selected Dark-Channel Prior Dehaze, YOLOv8n, Zone reasoning", duration_ms: 10 },
        { name: "Restoration (OpenCV Dehaze)", status: "completed", detail: "Applied Dark-Channel Prior atmospheric light recovery", duration_ms: 24 },
        { name: "Person detection (YOLOv8n)", status: "completed", detail: "1 person detected in hazardous automated corridor", duration_ms: 29 },
        { name: "Violation reasoning (Gemini)", status: "completed", detail: "1 critical unauthorized entry violation logged", duration_ms: 375 },
      ],
      detections: [
        {
          id: "p1",
          label: "Dock Worker 1",
          confidence: 0.91,
          box: { x: 555, y: 145, width: 95, height: 130 },
          source: "yolov8n_dehazed",
        },
      ],
      violations: [
        {
          id: "v1",
          type: "restricted_zone",
          severity: "critical",
          description: "Unescorted worker detected within the automated straddle carrier path during restricted crane hoist operations under zero-visibility protocol.",
          related_detection_ids: ["p1"],
          oshaCode: "OSHA 1917.151 / Maritime Standard",
          recommendation: "E-Stop automatic gantry traverse and alert Port Operations Center.",
        },
      ],
      annotated_image: "https://images.unsplash.com/photo-1706499856012-14f062c72b49?w=1600&q=80&auto=format&fit=crop",
      raw_image: "https://images.unsplash.com/photo-1706499856012-14f062c72b49?w=1600&q=80&auto=format&fit=crop",
      restored_image: "https://images.unsplash.com/photo-1706499856012-14f062c72b49?w=1600&q=80&auto=format&fit=crop",
    },
  },
  {
    id: "dust-open-pit-mine",
    title: "Open-Pit Mine Dust Storm",
    site: "Apex Copper Mine — Haul Road Ramp #2",
    camera: "CAM-08 (Pit Crest East)",
    condition: "High Dust Particulate (PM10 > 450)",
    tag: "Dust Storm",
    description: "Heavy 200-ton haul truck pass creates a dense dust plume blinding fixed CCTV models. Discern engages combined Dehazing and Bilateral Denoising to isolate pedestrian surveyors.",
    photoUrl: "https://images.unsplash.com/photo-1622645636770-11fbf0611463?w=1600&q=80&auto=format&fit=crop",
    photoCredit: "Unsplash",
    rawFilter: "sepia(0.45) brightness(0.8) contrast(0.85) saturate(1.3)",
    restoredFilter: "sepia(0.08) brightness(1.05) contrast(1.1) saturate(1.05)",
    analysis: {
      scene: {
        setting: "Open-pit mine haul road, mineral extraction ramp, heavy haul truck",
        lighting: "bright",
        weather: "dust",
        visibility: "poor",
        human_presence: true,
        machinery_presence: true,
        summary: "High particulate mineral dust dispersion on haul ramp reducing contrast and edge definition.",
      },
      plan: {
        restoration_tools: ["dehaze", "denoise"],
        detection_tools: ["person_detection", "ppe_reasoning", "zone_reasoning"],
        reasoning: "High-frequency dust noise and yellow-brown Rayleigh scattering obscuring haul truck blindspots. Bilateral filter and dehaze selected.",
      },
      steps: [
        { name: "Scene understanding", status: "completed", detail: "Open-pit mine, heavy dust storm, haul truck traffic present", duration_ms: 410 },
        { name: "Tool selection", status: "completed", detail: "Selected Dehaze + Bilateral Denoise, YOLOv8n, Unsafe Proximity", duration_ms: 11 },
        { name: "Restoration (Dehaze + Denoise)", status: "completed", detail: "Bilateral filter (d=9, sigma=75) + Dehaze", duration_ms: 32 },
        { name: "Person detection (YOLOv8n)", status: "completed", detail: "1 surveyor detected near haul truck blind spot", duration_ms: 34 },
        { name: "Violation reasoning (Gemini)", status: "completed", detail: "1 critical proximity violation flagged", duration_ms: 390 },
      ],
      detections: [
        {
          id: "p1",
          label: "Surveyor",
          confidence: 0.89,
          box: { x: 530, y: 380, width: 70, height: 155 },
          source: "yolov8n_denoised",
        },
      ],
      violations: [
        {
          id: "v1",
          type: "unsafe_proximity",
          severity: "critical",
          description: "Pedestrian surveyor walking within the 25-meter blind spot of a reversing 240-ton CAT 793F haul truck during dust-obscured conditions.",
          related_detection_ids: ["p1"],
          oshaCode: "MSHA 30 CFR § 56.9100",
          recommendation: "Activate proximity warning audio beacon on in-cab truck display.",
        },
      ],
      annotated_image: "https://images.unsplash.com/photo-1622645636770-11fbf0611463?w=1600&q=80&auto=format&fit=crop",
      raw_image: "https://images.unsplash.com/photo-1622645636770-11fbf0611463?w=1600&q=80&auto=format&fit=crop",
      restored_image: "https://images.unsplash.com/photo-1622645636770-11fbf0611463?w=1600&q=80&auto=format&fit=crop",
    },
  },
  {
    id: "glare-steel-refinery",
    title: "Solar Glare & High Contrast",
    site: "Vulcan Steel Mill — Outdoor Coil Storage",
    camera: "CAM-02 (Storage Yard Mast)",
    condition: "Direct Solar Glare & Harsh Shadows",
    tag: "High Glare",
    description: "Low winter sun reflecting off galvanized steel sheet coils causes extreme overexposure and deep shadows. Discern adapts dynamic range compensation to inspect worker PPE.",
    photoUrl: "https://images.unsplash.com/photo-1586472003620-73184ff05c4a?w=1600&q=80&auto=format&fit=crop",
    photoCredit: "Roman Chukhin / Unsplash",
    rawFilter: "brightness(1.4) contrast(1.35) saturate(0.55)",
    restoredFilter: "brightness(1.02) contrast(1.05) saturate(1.05)",
    analysis: {
      scene: {
        setting: "Outdoor industrial metal yard, direct sunlight reflection, overhead crane",
        lighting: "bright",
        weather: "glare",
        visibility: "reduced",
        human_presence: true,
        machinery_presence: true,
        summary: "Intense solar specular reflection off metallic surfaces creating sensor saturation and blown highlights.",
      },
      plan: {
        restoration_tools: ["low_light_enhancement"],
        detection_tools: ["person_detection", "ppe_reasoning"],
        reasoning: "High dynamic range imbalance. Local adaptive tone mapping applied to recover shadowed worker features without clipping highlights.",
      },
      steps: [
        { name: "Scene understanding", status: "completed", detail: "Steel storage yard, severe specular glare and shadow contrast", duration_ms: 370 },
        { name: "Tool selection", status: "completed", detail: "Selected Adaptive Tone Mapping, YOLOv8n, PPE reasoning", duration_ms: 9 },
        { name: "Restoration (OpenCV Tone Map)", status: "completed", detail: "Applied local tone curve compression", duration_ms: 19 },
        { name: "Person detection (YOLOv8n)", status: "completed", detail: "2 riggers detected in shaded bay", duration_ms: 28 },
        { name: "Violation reasoning (Gemini)", status: "completed", detail: "1 warning violation logged (Missing Hi-Vis Vest)", duration_ms: 365 },
      ],
      detections: [
        {
          id: "p1",
          label: "Rigger 1",
          confidence: 0.93,
          box: { x: 145, y: 430, width: 100, height: 170 },
          source: "yolov8n_tonemapped",
        },
      ],
      violations: [
        {
          id: "v1",
          type: "missing_ppe",
          severity: "warning",
          description: "Worker (Person 1) wearing dark outerwear without ANSI/ISEA 107-2020 Class 2 High-Visibility reflective apparel in yard with mobile forklifts.",
          related_detection_ids: ["p1"],
          oshaCode: "OSHA 1926.201 / ANSI 107",
          recommendation: "Issue hi-vis vest reminder at yard check-in turnstile.",
        },
      ],
      annotated_image: "https://images.unsplash.com/photo-1586472003620-73184ff05c4a?w=1600&q=80&auto=format&fit=crop",
      raw_image: "https://images.unsplash.com/photo-1586472003620-73184ff05c4a?w=1600&q=80&auto=format&fit=crop",
      restored_image: "https://images.unsplash.com/photo-1586472003620-73184ff05c4a?w=1600&q=80&auto=format&fit=crop",
    },
  },
  {
    id: "clear-control-test",
    title: "Clear Daytime (Control Benchmark)",
    site: "Titan Logistics Hub — Main Yard",
    camera: "CAM-01 (Gate Control Tower)",
    condition: "Clear Sunlight / 85,000 Lux",
    tag: "Clear Weather",
    description: "Benchmark test in optimal weather conditions. Discern's agent intelligently skips restoration steps, saving compute cycles and latency while directly running person detection and compliance checks.",
    photoUrl: "https://images.unsplash.com/photo-1611816951577-198c5dcf0e96?w=1600&q=80&auto=format&fit=crop",
    photoCredit: "Unsplash",
    rawFilter: "none",
    restoredFilter: "none",
    analysis: {
      scene: {
        setting: "Logistics staging yard, concrete apron, gate barrier",
        lighting: "bright",
        weather: "clear",
        visibility: "good",
        human_presence: true,
        machinery_presence: false,
        summary: "Optimal daylight conditions with high ambient contrast and no atmospheric degradation.",
      },
      plan: {
        restoration_tools: [],
        detection_tools: ["person_detection", "ppe_reasoning"],
        reasoning: "Frame conditions are pristine (clear weather, good visibility, 85,000 Lux). Restoration bypassed completely to minimize latency and conserve GPU compute.",
      },
      steps: [
        { name: "Scene understanding", status: "completed", detail: "Clear daylight yard, excellent visibility, pedestrians present", duration_ms: 320 },
        { name: "Tool selection", status: "completed", detail: "Restoration skipped; direct dispatch to YOLOv8n & PPE check", duration_ms: 8 },
        { name: "Restoration", status: "skipped", detail: "Frame conditions did not warrant restoration (0ms compute saved)", duration_ms: 0 },
        { name: "Person detection (YOLOv8n)", status: "completed", detail: "1 person detected with 98% confidence", duration_ms: 22 },
        { name: "Violation reasoning (Gemini)", status: "completed", detail: "Full PPE compliance verified, zero violations", duration_ms: 310 },
      ],
      detections: [
        {
          id: "p2",
          label: "Site Inspector",
          confidence: 0.98,
          box: { x: 220, y: 410, width: 68, height: 148 },
          source: "yolov8n_direct",
        },
      ],
      violations: [],
      annotated_image: "https://images.unsplash.com/photo-1611816951577-198c5dcf0e96?w=1600&q=80&auto=format&fit=crop",
      raw_image: "https://images.unsplash.com/photo-1611816951577-198c5dcf0e96?w=1600&q=80&auto=format&fit=crop",
      restored_image: "https://images.unsplash.com/photo-1611816951577-198c5dcf0e96?w=1600&q=80&auto=format&fit=crop",
    },
  },
  {
    id: "fog-highway-traffic",
    title: "HazyDet Drone Overwatch",
    site: "Urban Corridor — Aerial Traffic Survey",
    camera: "CAM-21 (Drone Overwatch, 120m AGL)",
    condition: "Dense Fog / Visibility < 60m",
    tag: "Highway Fog",
    description: "Real sample frame from HazyDet (Feng et al., 2024), the drone-view hazy-scene object-detection benchmark used to evaluate the agentic-restoration research (DetAS, Zhang et al., 2026) this app is built on. Discern dehazes the frame before running YOLOv8n to localize every car, truck, and motorcycle below.",
    photoUrl: "/samples/hazydet-street-fog-1.jpg",
    photoCredit: "HazyDet dataset (Feng et al., 2024), used for research/benchmark purposes",
    rawFilter: "brightness(1.1) contrast(0.6) saturate(0.5) blur(1px)",
    restoredFilter: "contrast(1.2) saturate(1.1) brightness(1.02)",
    analysis: {
      scene: {
        setting: "Multi-lane interstate highway, elevated overpass camera, dense traffic",
        lighting: "normal",
        weather: "fog",
        visibility: "poor",
        human_presence: false,
        machinery_presence: true,
        summary: "Thick ground fog bank reducing highway visibility to under 60 meters with heavy multi-lane vehicle traffic.",
      },
      plan: {
        restoration_tools: ["dehaze"],
        detection_tools: ["person_detection"],
        reasoning: "Visibility is severely reduced by fog scattering. Dark-Channel Prior dehazing applied to recover lane markings and vehicle edges before running multi-class YOLOv8n detection (car/truck/motorcycle/bicycle/person).",
      },
      steps: [
        { name: "Scene understanding", status: "completed", detail: "Highway overpass, dense fog, heavy vehicle traffic", duration_ms: 360 },
        { name: "Tool selection", status: "completed", detail: "Selected Dark-Channel Prior Dehaze, multi-class YOLOv8n", duration_ms: 9 },
        { name: "Restoration (OpenCV Dehaze)", status: "completed", detail: "Applied Dark-Channel Prior atmospheric light recovery", duration_ms: 21 },
        { name: "Object detection (YOLOv8n)", status: "completed", detail: "6 vehicles localized across 3 lanes", duration_ms: 33 },
        { name: "Violation reasoning", status: "skipped", detail: "No people in frame; PPE/zone checks not applicable", duration_ms: 0 },
      ],
      detections: [
        { id: "v1", label: "car", confidence: 0.93, box: { x: 210, y: 430, width: 150, height: 90 }, source: "yolov8n_dehazed" },
        { id: "v2", label: "car", confidence: 0.89, box: { x: 430, y: 400, width: 130, height: 80 }, source: "yolov8n_dehazed" },
        { id: "v3", label: "truck", confidence: 0.91, box: { x: 700, y: 350, width: 190, height: 130 }, source: "yolov8n_dehazed" },
        { id: "v4", label: "car", confidence: 0.85, box: { x: 950, y: 460, width: 140, height: 85 }, source: "yolov8n_dehazed" },
      ],
      violations: [],
      annotated_image: "/samples/hazydet-street-fog-1.jpg",
      raw_image: "/samples/hazydet-street-fog-1.jpg",
      restored_image: "/samples/hazydet-street-fog-1.jpg",
    },
  },
  {
    id: "rain-street-crossing",
    title: "Rainy Street Crossing",
    site: "Downtown Arterial — 5th & Main",
    camera: "CAM-15 (Signal Mast)",
    condition: "Heavy Rain / Wet Pavement",
    tag: "Heavy Rain",
    description: "Rain speckle and reflective wet asphalt degrade a busy downtown crosswalk feed. Discern denoises the rain streaks before localizing pedestrians and vehicles, then reasons about unsafe roadway proximity.",
    photoUrl: "https://images.unsplash.com/photo-1576514864427-f0809d2b66eb?w=1600&q=80&auto=format&fit=crop",
    photoCredit: "Gil Ribeiro / Unsplash",
    rawFilter: "brightness(0.75) contrast(0.85) saturate(0.6) blur(0.6px)",
    restoredFilter: "brightness(1.08) contrast(1.15) saturate(1.05)",
    analysis: {
      scene: {
        setting: "Downtown crosswalk and arterial street, wet pavement, pedestrian traffic",
        lighting: "low_light",
        weather: "rain",
        visibility: "reduced",
        human_presence: true,
        machinery_presence: false,
        summary: "Heavy rainfall over a downtown pedestrian crossing, with rain streaks and wet-pavement glare degrading sensor contrast.",
      },
      plan: {
        restoration_tools: ["denoise", "low_light_enhancement"],
        detection_tools: ["person_detection", "zone_reasoning"],
        reasoning: "Rain speckle and low ambient light both degrade the frame. Bilateral denoising removes rain-streak noise, then CLAHE recovers pedestrian contrast, before multi-class YOLOv8n localizes people and any nearby vehicles.",
      },
      steps: [
        { name: "Scene understanding", status: "completed", detail: "Downtown crosswalk, heavy rain, pedestrians present", duration_ms: 340 },
        { name: "Tool selection", status: "completed", detail: "Selected Denoise + CLAHE, multi-class YOLOv8n, zone reasoning", duration_ms: 10 },
        { name: "Restoration (Denoise + CLAHE)", status: "completed", detail: "Bilateral filter (d=9) + CLAHE contrast recovery", duration_ms: 27 },
        { name: "Object detection (YOLOv8n)", status: "completed", detail: "3 pedestrians localized in crosswalk", duration_ms: 30 },
        { name: "Violation reasoning (Gemini)", status: "completed", detail: "1 warning proximity violation logged", duration_ms: 340 },
      ],
      detections: [
        { id: "p1", label: "person", confidence: 0.9, box: { x: 250, y: 380, width: 90, height: 200 }, source: "yolov8n_denoised" },
        { id: "p2", label: "person", confidence: 0.87, box: { x: 420, y: 400, width: 85, height: 190 }, source: "yolov8n_denoised" },
      ],
      violations: [
        {
          id: "v1",
          type: "unsafe_proximity",
          severity: "warning",
          description: "Pedestrian (Person 1) is stepping off the curb into the active traffic lane before the crossing signal, reducing visible reaction time for approaching vehicles in wet-braking conditions.",
          related_detection_ids: ["p1"],
          oshaCode: "MUTCD Ch. 4E",
          recommendation: "Flag for traffic-signal timing review at this intersection.",
        },
      ],
      annotated_image: "https://images.unsplash.com/photo-1576514864427-f0809d2b66eb?w=1600&q=80&auto=format&fit=crop",
      raw_image: "https://images.unsplash.com/photo-1576514864427-f0809d2b66eb?w=1600&q=80&auto=format&fit=crop",
      restored_image: "https://images.unsplash.com/photo-1576514864427-f0809d2b66eb?w=1600&q=80&auto=format&fit=crop",
    },
  },
  {
    id: "night-traffic-glare",
    title: "Night Traffic Headlight Glare",
    site: "Ring Road Junction — Overpass 12",
    camera: "CAM-33 (Junction Mast)",
    condition: "Night / Headlight Glare",
    tag: "Night Glare",
    description: "Oncoming headlights blow out sensor highlights on a busy night junction. Discern compensates dynamic range before running multi-class detection across the full vehicle stream.",
    photoUrl: "https://images.unsplash.com/photo-1699586747892-c2b9eeeb0327?w=1600&q=80&auto=format&fit=crop",
    photoCredit: "Unsplash",
    rawFilter: "brightness(0.85) contrast(1.5) saturate(0.8)",
    restoredFilter: "brightness(1.0) contrast(1.05) saturate(1.05)",
    analysis: {
      scene: {
        setting: "Multi-lane ring-road junction at night, overpass camera, dense vehicle stream",
        lighting: "night",
        weather: "clear",
        visibility: "reduced",
        human_presence: false,
        machinery_presence: true,
        summary: "Nighttime junction with oncoming headlight glare causing sensor highlight clipping across multiple lanes of moving traffic.",
      },
      plan: {
        restoration_tools: ["low_light_enhancement"],
        detection_tools: ["person_detection"],
        reasoning: "Headlight glare blows out highlights while surrounding areas stay underexposed. Adaptive tone compensation recovers both ends of the dynamic range before multi-class YOLOv8n vehicle detection.",
      },
      steps: [
        { name: "Scene understanding", status: "completed", detail: "Night junction, headlight glare, heavy vehicle stream", duration_ms: 355 },
        { name: "Tool selection", status: "completed", detail: "Selected Adaptive Tone Mapping, multi-class YOLOv8n", duration_ms: 8 },
        { name: "Restoration (OpenCV Tone Map)", status: "completed", detail: "Local tone curve compression on highlight-clipped regions", duration_ms: 20 },
        { name: "Object detection (YOLOv8n)", status: "completed", detail: "5 vehicles localized despite glare", duration_ms: 29 },
        { name: "Violation reasoning", status: "skipped", detail: "No people in frame; PPE/zone checks not applicable", duration_ms: 0 },
      ],
      detections: [
        { id: "v1", label: "car", confidence: 0.88, box: { x: 300, y: 420, width: 140, height: 90 }, source: "yolov8n_tonemapped" },
        { id: "v2", label: "car", confidence: 0.84, box: { x: 560, y: 440, width: 130, height: 85 }, source: "yolov8n_tonemapped" },
        { id: "v3", label: "truck", confidence: 0.9, box: { x: 780, y: 380, width: 180, height: 120 }, source: "yolov8n_tonemapped" },
      ],
      violations: [],
      annotated_image: "https://images.unsplash.com/photo-1699586747892-c2b9eeeb0327?w=1600&q=80&auto=format&fit=crop",
      raw_image: "https://images.unsplash.com/photo-1699586747892-c2b9eeeb0327?w=1600&q=80&auto=format&fit=crop",
      restored_image: "https://images.unsplash.com/photo-1699586747892-c2b9eeeb0327?w=1600&q=80&auto=format&fit=crop",
    },
  },
];

export const SAMPLE_CAMERAS: CameraFeed[] = [
  {
    id: "cam-04",
    name: "CAM-04 · North Excavation",
    location: "North Industrial Excavation",
    zone: "Zone 4 Heavy Equipment",
    status: "alert",
    fps: 30,
    resolution: "1920x1080",
    lux: 12.4,
    weatherCondition: "Low-Light / Dawn",
    violationsCount: 2,
    lastChecked: "Just now",
    presetId: "dawn-construction",
  },
  {
    id: "cam-12",
    name: "CAM-12 · Quay Gantry South",
    location: "Port Logistics Terminal",
    zone: "Berth 7 Automated Corridor",
    status: "alert",
    fps: 25,
    resolution: "2560x1440",
    lux: 180.0,
    weatherCondition: "Dense Fog",
    violationsCount: 1,
    lastChecked: "2m ago",
    presetId: "fog-maritime-port",
  },
  {
    id: "cam-08",
    name: "CAM-08 · Pit Crest East",
    location: "Apex Copper Mine",
    zone: "Haul Ramp #2 Intersection",
    status: "alert",
    fps: 30,
    resolution: "1920x1080",
    lux: 940.0,
    weatherCondition: "Dust Plume",
    violationsCount: 1,
    lastChecked: "5m ago",
    presetId: "dust-open-pit-mine",
  },
  {
    id: "cam-01",
    name: "CAM-01 · Gate Control Tower",
    location: "Titan Logistics Hub",
    zone: "Main Gate Checkpoint",
    status: "active",
    fps: 60,
    resolution: "3840x2160",
    lux: 85000.0,
    weatherCondition: "Clear Day",
    violationsCount: 0,
    lastChecked: "1m ago",
    presetId: "clear-control-test",
  },
];

export const SAMPLE_AUDIT_LOGS: AuditRecord[] = [
  {
    id: "AUD-8921",
    timestamp: "2026-09-15 05:42:19",
    cameraId: "CAM-04",
    cameraName: "North Excavation Perimeter",
    zone: "Zone 4 Trench",
    weather: "Dawn / 12 Lux",
    lighting: "Low Light",
    violationType: "Missing Hard Hat + Machinery Proximity",
    severity: "critical",
    description: "Worker inside 15m excavator swing radius without approved helmet. CLAHE + Gamma restoration applied before detection.",
    restorationApplied: "CLAHE + Gamma (18ms)",
    status: "open",
  },
  {
    id: "AUD-8920",
    timestamp: "2026-09-15 05:38:04",
    cameraId: "CAM-12",
    cameraName: "Quay Gantry South",
    zone: "Berth 7 Quay",
    weather: "Dense Fog",
    lighting: "Normal",
    violationType: "Restricted Automated Zone Breach",
    severity: "critical",
    description: "Pedestrian in automated straddle corridor during hoist maneuver. Dehaze restored visibility from 25m to 120m.",
    restorationApplied: "Dark-Channel Prior Dehaze (24ms)",
    status: "acknowledged",
  },
  {
    id: "AUD-8919",
    timestamp: "2026-09-15 05:14:52",
    cameraId: "CAM-08",
    cameraName: "Pit Crest East",
    zone: "Haul Ramp #2",
    weather: "Mine Dust Plume",
    lighting: "Bright",
    violationType: "Haul Truck Blindspot Intrusion",
    severity: "critical",
    description: "Surveyor walking within 25m blindspot of reversing CAT 793F truck. Bilateral denoise + dehaze engaged.",
    restorationApplied: "Bilateral Filter + Dehaze (32ms)",
    status: "resolved",
  },
  {
    id: "AUD-8918",
    timestamp: "2026-09-15 04:59:11",
    cameraId: "CAM-02",
    cameraName: "Storage Yard Mast",
    zone: "Coil Storage Bay",
    weather: "Specular Glare",
    lighting: "High Contrast",
    violationType: "Missing Hi-Vis Apparel",
    severity: "warning",
    description: "Worker in dark clothing in high-traffic forklift transit bay. Adaptive tone mapping recovered shadow detail.",
    restorationApplied: "Tone Map Compression (19ms)",
    status: "resolved",
  },
  {
    id: "AUD-8917",
    timestamp: "2026-09-15 04:30:00",
    cameraId: "CAM-01",
    cameraName: "Gate Control Tower",
    zone: "Turnstile Gate",
    weather: "Clear",
    lighting: "Daylight",
    violationType: "None (Full Compliance)",
    severity: "info",
    description: "Periodic shift inspection. Scene classified as pristine; restoration bypassed dynamically (0ms latency penalty).",
    restorationApplied: "Skipped (Bypassed)",
    status: "resolved",
  },
];
